%YAML:1.0
# This file is obsolete, and only used to test pre-2.0 versions of chilitags.
# Use tags_configuration_sample.yml instead

myobject1:
    - marker: 0
      size: 20

myobject2:
    - marker: 1
      size: 30
      translation: [10., 0., 0.]
      rotation: [0., 0., 90.]

myobject3:
    - marker: 2
      size: 20
      translation: [-50., -100., 0.0]
      keep: true
    - marker: 3
      size: 30
      translation: [50., -100., 0.0]
    - marker: 4
      size: 30
      translation: [50., 100., 0.0]

